language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip uninstall -y numpy
  - pip install git+https://github.com/nakagami/minipg.git
  - python setup.py install
  - (cd /tmp; wget https://pypi.python.org/packages/source/D/Django/Django-1.7.7.tar.gz; tar zxf Django-1.7.7.tar.gz)
  - (cd /tmp; wget https://pypi.python.org/packages/source/D/Django/Django-1.8.tar.gz; tar zxf Django-1.8.tar.gz)
  - cp test_minipg.py /tmp/Django-1.7.7/tests
  - cp test_minipg.py /tmp/Django-1.8/tests

script:
  - (cd /tmp/Django-1.7.7/tests; PYTHONPATH='..' python runtests.py --settings=test_minipg)
  - (cd /tmp/Django-1.8/tests; PYTHONPATH='..' python runtests.py --settings=test_minipg)
