language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - pip install git+https://github.com/nakagami/minipg.git
  - python setup.py install
  - (cd /tmp; wget https://pypi.python.org/packages/source/D/Django/Django-1.7.1.tar.gz; tar zxf Django-1.7.1.tar.gz)
  - cp test_minipg.py /tmp/Django-1.7.1/tests

script:
  - (cd /tmp/Django-1.7.1/tests; PYTHONPATH='..' python runtests.py --settings=test_minipg)
