dist: trusty
language: python
sudo: false
python:
  - "3.5"
  - "3.6"
#  - "3.7"

install:
  - pip install -U pip
  - pip install pytz
  - pip install git+https://github.com/nakagami/minipg.git
  - python setup.py install
  - (cd /tmp; wget https://github.com/django/django/archive/2.2.tar.gz; tar zxf 2.2.tar.gz)
  - cp test_minipg.py /tmp/django-2.2/tests
  - cd /tmp/django-2.2/tests
  - pip install -e ..
  - pip install -r requirements/py3.txt

script:
  - cd /tmp/django-2.2/tests
  - ./runtests.py --settings=test_minipg --noinput
